import { Component, ViewEncapsulation } from '@angular/core';
import { Router } from '@angular/router';
import { Injectable } from '@angular/core';
import {HttpClient, HttpParams, HttpRequest, HttpEvent,HttpEventType} from '@angular/common/http';
import {MatIconModule} from '@angular/material/icon';


@Component({
  selector: 'summarization',
  templateUrl: './summary.summarization.html',
  styleUrls: ['./summary.summarization.css'],
  encapsulation: ViewEncapsulation.None
})
export class AppSummarizationComponent {
  size=0;
  fileName = '';
  summaryList: any = [];
  showLoader = false;
  dict: any = {
    revenue: "money regularly received by a government, company, etc.",
    revenues: "money regularly received by a government, company, etc.",
    income: "the money you receive regularly as payment for your work or as interest on money you have saved, etc.",
    profits: "the money that you make when you sell something for more than it cost you",

    effective: {
      space: {
        tax: "The taxes levied on all the taxable incomes is termed as the effective tax."
      }
    },
    tax: {
      space: {
        rate: "The tax rate is the percentage of an income or an amount of money that has to be paid as tax"
      }
    },
    cash: {
      space: {
        flow: "Cash flow is the movement of money in and out of a company",
        flows:"Cash flow is the movement of money in and out of a company"
      }
    },
    capital: {
      space: {
        ratio: "The working capital ratio is calculated simply by dividing total current assets by total"
      }
    },
    net: {
      space: {
        income: "Net income refers to the amount an individual or business makes after deducting costs, allowances and taxes",
        profit: "Net profit is the amount of money your business earns after deducting all operating, interest, and tax expenses over a given period of time",
        sales: "Net sales is the sum of a company's gross sales minus its returns, allowances, and discounts"
      }
    },
    operating: {
      space: {
        expenses:"An operating expense is an expense that a business incurs through its normal business operations",
        cash: "Operating Cash Flow (OCF) is the amount of cash generated by the regular operating activities of a business within a specific time period."

      }
    },
    diluted: {
      space: {
        earnings: "Diluted earnings per share (EPS) is a measurement of a company's earnings per share if all convertible securities were converted"

      }
    },
    tangible: {
      space:{
        equity:"Tangible common equity (TCE) is a measure of a company's physical capital, which is used to evaluate a financial institution's ability to deal with potential losses"

      }
    }
  };
  constructor(private http: HttpClient) {}

  onFileSelected(event: any) {

      const file:File = event.target.files[0];

      if (file) {
          this.showLoader = true;
          this.fileName = file.name;
          
          const formData = new FormData();

          formData.append("file", file);
          //var option = {'Content-Length' : msg.length, 'Content-Type': 'plain/text', 'body' : msg};

          const upload$ = this.http.post("http://192.168.211.65:5000/upload", formData);
          let map = new Map();  
  
          map.set('cash flow', 'cash flow tooltip');     

          upload$.subscribe((data: any) => {
            // let obj = {
            //   "summaryOfFile": [
            //     " \n\nThis quarterly financial report presents a summary of the financial results of our company for the third quarter of 2020. The report provides an overview of revenue, operating expenses, net profit/loss, and other key metrics. It also includes commentary on significant changes or trends in the company's financial performance.",
            //     " This Quarterly Financial Report / Third Quarter 2020 contains key figures, information about the company, share performance, an interim management report, consolidated interim financial statements, notes to the financial statements, and additional information.",
            //     " \n This Quarterly Financial Report presents the key figures for Q3 2020 and Q3 2019, as well as Q1-Q3 2020 and Q1-Q3 2019. The total sales decreased by 2.7% from 156,225 K\u20ac to 152,007 K\u20ac, operating profit increased by 0.5% from 16,059 K\u20ac to 16,138 K\u20ac, EBIT margin increased by 0.3 Pp from 10.3 to 10.6, net income decreased by 1.3% from 11,427 K\u20ac to 11,279 K\u20ac, return on sales increased by 0.1 Pp from 7.3 to 7.4, operating cash",
            //     " The sentiment of this text is positive, as the company has shown continued growth and success. They have also maintained a healthy balance sheet and cash flow."
            //   ]
            // }
            // this.summaryList = obj.summaryOfFile
            this.summaryList = data.summaryOfFile
            this.size = this.summaryList.length - 1;
            this.showLoader = false
            let index = 0;
            this.summaryList.forEach((summary:any)=>{
              let words = summary.split(" ");
              let wordsIndex = 0;
              words.forEach((word: string) => {
                let wordLowerCase = word.toLowerCase()
                if(wordLowerCase?.includes(',')) wordLowerCase = wordLowerCase.split(',').join('')
                if(this.dict[wordLowerCase] && this.dict[wordLowerCase].space == undefined) {
                  console.log('actual',wordLowerCase, word)
                  summary = summary.replace(word, '<div class="tooltip">' + word + '<span class="tooltiptext">' + this.dict[wordLowerCase] + '</span></div>');
                } else if(this.dict[word] && this.dict[word].space != undefined) {
                  let nextWord = words[wordsIndex+1]
                  let lowerCaseNextWord = nextWord?.toLowerCase()
                  // nextWord = nextWord.toLowerCase()
                  if(lowerCaseNextWord?.includes(',')) lowerCaseNextWord = lowerCaseNextWord.split(',').join('')
                  console.log('2 word',word+' '+nextWord);
                  if(this.dict[wordLowerCase].space[lowerCaseNextWord]) {
                    console.log('2 word passed',word+' '+nextWord);
                    summary = summary.replace(word+' '+nextWord, '<div class="tooltip">' + word+' '+nextWord + '<span class="tooltiptext">' + this.dict[wordLowerCase].space[lowerCaseNextWord] + '</span></div>');
                  }
                }
                wordsIndex++
              })
              this.summaryList[index] = summary.replace('net profit', '<div class="tooltip">net profit<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('profit before tax', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('operating profit', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('EBIT margin', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('cash equivalents', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('net income', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('earnings per share', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('capital expenditures', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('effective tax', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('tax rate', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('cash flow', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('capital ratio', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('net sales', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('opeating expenses', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('diluted earnings', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('tangible equity', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('cash flows', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('comprehensive income', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');
              this.summaryList[index] = summary.replace('operating cash flow', '<div class="tooltip">profit before tax<span class="tooltiptext">Tooltip text</span></div>');

              index +=1
            })
          }, (error) => {
            console.log("error",error)
          });
      }

  
}

}